# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[wallpaper]
 custom_paths = [
    "$HOME/Pictures/Wallpapers",
]

[battery.notify]
dock = true
